Basics Of Pandas


In [1]:
#Libraries
import numpy as np
import pandas as pd

In [2]:
#List Initialazation
arr=np.random.randint(0,100,(5,5))

In [3]:
print(arr)

[[94 47 26  6 93]
 [98 19 55 17 60]
 [75 55 14 41  6]
 [45 39 52  7 93]
 [49 35 13 12 10]]


In [4]:
#Convert Into Data table
df=pd.DataFrame(arr)
df

0   1   2   3   4
0  94  47  26   6  93
1  98  19  55  17  60
2  75  55  14  41   6
3  45  39  52   7  93
4  49  35  13  12  10

In [5]:
#Now I Want to Change The Row And Colum Name
Row=["AIDS","AIML","ECE","CSBS","MECH"]
Col=["PSC","PYTHON","DSA","HTML","CSS"]

In [6]:
df=pd.DataFrame(arr,index=Row,columns=Col)
print(df)

      PSC  PYTHON  DSA  HTML  CSS
AIDS   94      47   26     6   93
AIML   98      19   55    17   60
ECE    75      55   14    41    6
CSBS   45      39   52     7   93
MECH   49      35   13    12   10


In [7]:
#Using Dictionarys
myDic={
    'Jan':[1,2,3,4,5],
    'Feb':[5,6,7,8,9],
    'Mar':[10,11,12,13,14]
}


In [8]:
print(myDic)

{'Jan': [1, 2, 3, 4, 5], 'Feb': [5, 6, 7, 8, 9], 'Mar': [10, 11, 12, 13, 14]}


In [9]:
df=pd.DataFrame(myDic,index=["Q","W","E","R","S"])

In [10]:
print(df)

   Jan  Feb  Mar
Q    1    5   10
W    2    6   11
E    3    7   12
R    4    8   13
S    5    9   14


In [11]:
#Upload CSV Files
df=pd.read_csv('/content/sample_data/california_housing_test.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/california_housing_test.csv'

In [ ]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
#If You Want To See The First 5 Line Of data 
#use pd.head()
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  


In [ ]:
#If You Want To See The Last 5 Line Of data 
#use pd.tail()
print(df.tail())

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  


In [ ]:
#To Find The How Many Rows And Colunms Are There In The Data
# Variable_name.shape
print(df.shape)

(3000, 9)


In [ ]:
#If you convert the data into list format 
# variable_name.values
print(df.values)