In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr=np.random.randint(1,100,(5,4))
arr

array([[58, 43, 17, 46],
       [54, 99, 99, 63],
       [ 7, 50, 70, 21],
       [40, 64, 20, 27],
       [51, 29, 56, 72]])

In [ ]:
df=pd.DataFrame(arr,columns=list('abcd'))

In [ ]:
df

a   b   c   d
0  58  43  17  46
1  54  99  99  63
2   7  50  70  21
3  40  64  20  27
4  51  29  56  72

Extract Only One Column There fore the colomn of the frame work is called **SERIES**

In [ ]:
df['a']

0    58
1    54
2     7
3    40
4    51
Name: a, dtype: int64

In [ ]:
#To Slice The Series 
df['a'][0:3]

0    58
1    54
2     7
Name: a, dtype: int64

In [ ]:
#If You Convert Into the Array Format
df['a'][0:3].values

array([58, 54,  7])

In [ ]:
#Convert Into List
df['a'][0:3].values.tolist()

[58, 54, 7]

Series Creation

In [ ]:
#Create a Series
arr=np.arange(10)
df=pd.Series(data=[1,2,3,4,5,6],name='Abu')

In [ ]:
df

0    1
1    2
2    3
3    4
4    5
5    6
Name: Abu, dtype: int64

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
arr=[1,2,23,43,4,54,4]

In [ ]:
ds=pd.Series(data=arr)

In [ ]:
ds

0     1
1     2
2    23
3    43
4     4
5    54
6     4
dtype: int64

In [ ]:
arr=[[1,2,3],[4,5,6],[7,8,9]]
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
type(arr)

list

In [ ]:
arr*2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
se=pd.Series(data=arr[0],index=['a','b','c'])

In [ ]:
se

a    1
b    2
c    3
dtype: int64

In [ ]:
se*3

a    3
b    6
c    9
dtype: int64

**IMPORTENT NOTE IS**
-->If we multiply in a list the list will repeate the values 
-->If we Multiply The Value in a Series It Multiply In Scalar Values
**EXAMPLE**
arr=[1,2,3,4]
arr*2-->[1,2,3,4,1,2,3,4]

se=pd.Series(arr[0])
se*2-->[2,4,6,8]

In [ ]:
#If We Seperate Every Single Element In The Series  use this method
#SYNTAX series_name[index]
se['a']

1

In [ ]:
#If We want Extract More then One Value From The series we pass like this
se[['a','b']]
#Why We are putting Like This Because The series is the one dimentional Array When we send into a squre bracet in takes the one argument

a    1
b    2
dtype: int64

In [ ]:
se['a']*2

2

In [ ]:
se

a    1
b    2
c    3
dtype: int64

In [ ]:
#What are the indexes are in the list we can extract the indexes using key OR inex function
#SYNTAX var_name.index
'''OR'''
#SYNTAX varname.keys()
se.index 
se.keys()

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
#Using Dictionaries
l1={'a':0,'b':1,'c':3}
l2={'b':0,'c':1,'d':3}

In [ ]:
s1=pd.Series(l1)
s2=pd.Series(l2)

b    0
c    1
d    3
dtype: int64

In [ ]:
s1

a    0
b    1
c    3
dtype: int64

In [ ]:
s2

b    0
c    1
d    3
dtype: int64

In [ ]:
s1+s2

a    NaN
b    1.0
c    4.0
d    NaN
dtype: float64

In [ ]:
#Use Inbuild Fuction
#var_name1.add(var_name2,filvalue=0)
s1.add(s2)

a    NaN
b    1.0
c    4.0
d    NaN
dtype: float64

In [ ]:
s1.add(s2,fill_value=0)

a    0.0
b    1.0
c    4.0
d    3.0
dtype: float64

In [ ]:
s1.values+s2.values

array([0, 2, 6])